import Link from "next/link";
import { ArrowLeft, Scale } from "lucide-react";
import { PortalShell } from "@/components/portal/PortalShell";

const clauses = [
  ["1. Scope of service", "ConsultX provides a digital workflow to collect information, prepare an annual-return filing and, where authorised, assist with submission to CIPC. ConsultX is not CIPC and does not control CIPC systems, processing times, fees, availability or outcomes."],
  ["2. Client information and authority", "The client confirms that it is authorised to act for the company and that all information, declarations and documents it enters or uploads are complete, accurate and current. The client must promptly correct information that changes or is found to be inaccurate."],
  ["3. Client-completed filing information", "Where the client completes the workflow or supplies information for automated preparation, the client remains responsible for the accuracy, completeness and legality of that information. ConsultX may identify apparent gaps or inconsistencies, but this does not amount to an audit, verification, legal opinion or guarantee that the information is sufficient for CIPC purposes."],
  ["4. ConsultX-assisted completion", "If the client specifically engages ConsultX to help complete or review a filing, the scope of that assistance will be confirmed in writing. The client must still provide timely, accurate information and approve the final information and authority before submission."],
  ["5. Fees and payment", "The ConsultX service fee and estimated CIPC statutory fee are shown before payment. CIPC fees are subject to CIPC’s current rules and calculator. Any final difference will be disclosed before filing where possible. A payment to ConsultX does not itself confirm that CIPC has accepted a submission."],
  ["6. Submission and third parties", "Submission occurs only after the required authority and payment have been received. ConsultX may use approved technology providers to deliver the service. CIPC credentials must not be entered into the client portal; any future CIPC connection will use an approved secure method."],
  ["7. Liability and availability", "To the extent permitted by applicable law, ConsultX is not responsible for losses caused by inaccurate, incomplete or late client information, a client’s lack of authority, CIPC system availability, or CIPC’s decision on a filing. Nothing in these terms excludes liability that cannot lawfully be excluded."],
  ["8. Records and communications", "ConsultX may retain the client’s authorisation, inputs, documents, payment record, workflow history and CIPC confirmation for service delivery, compliance and audit purposes. The client agrees that operational notices and future-return reminders may be sent electronically."],
];

export default function CipcTermsPage() {
  return <PortalShell><div className="mx-auto max-w-4xl"><Link href="/portal/services/cipc-annual-return/" className="inline-flex items-center gap-2 text-sm font-bold text-consultx-charcoal hover:text-consultx-green-dark"><ArrowLeft className="h-4 w-4" />Return to annual return</Link><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><strong>Draft terms for legal review.</strong> These terms are an implementation draft and must be reviewed and approved by a South African legal adviser before publication or use with clients.</div><div className="mt-8 rounded-2xl border border-consultx-border bg-white p-6 shadow-soft md:p-10"><Scale className="h-7 w-7 text-consultx-green-dark" /><p className="mt-6 text-sm font-bold text-consultx-green-dark">CONSULTX CLIENT PORTAL</p><h1 className="mt-1 text-3xl font-bold tracking-tight md:text-4xl">CIPC Annual Return Service Terms</h1><p className="mt-3 text-sm leading-6 text-consultx-grey">Effective date: to be confirmed before launch</p><div className="mt-8 space-y-7">{clauses.map(([title, text]) => <section key={title}><h2 className="font-bold">{title}</h2><p className="mt-2 leading-7 text-consultx-charcoal">{text}</p></section>)}</div><div className="mt-8 border-t border-consultx-border pt-6 text-sm leading-6 text-consultx-grey">These terms sit alongside the applicable CIPC terms and conditions. If there is a conflict in relation to a CIPC service, the CIPC requirements apply.</div></div></div></PortalShell>;
}
