const fs = require('node:fs');
const ts = require('typescript');
const vm = require('node:vm');
const assert = require('node:assert/strict');
function load(file) {
  const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
  const exports = {};
  vm.runInNewContext(code, { exports, structuredClone, Date });
  return exports;
}
const { assessWorkflow } = load('src/lib/advisor-assessment.ts');
const { adaptPublicReply } = load('src/lib/advisor-response.ts');
let r = assessWorkflow('I want to assess automation opportunities across my business');
assert.equal(r.updatedProfile.assessment.scope, 'business');
assert.equal(r.blueprint, undefined);
r = assessWorkflow('We run a retail business. Month-end close and debtor follow-up are slow. We use Excel and Outlook.', r.updatedProfile);
assert.equal(r.opportunities.length, 2);
assert.equal(r.clarification.id, 'assessment_focus');
assert.equal(r.updatedProfile.primarySystems.includes('Xero'), false);
r = assessWorkflow('Month-end close', r.updatedProfile);
assert.equal(r.clarification.id, 'assessment_bottleneck');
r = assessWorkflow('Waiting for approvals', r.updatedProfile);
assert.equal(r.clarification.id, 'assessment_systems');
r = assessWorkflow('We use Acumatica', r.updatedProfile);
assert.equal(r.clarification.id, 'assessment_scale');
const before = JSON.stringify(r.updatedProfile.assessment.evidence);
r = assessWorkflow('What do you mean by volume?', r.updatedProfile);
assert.equal(r.clarification.id, 'assessment_scale');
assert.equal(JSON.stringify(r.updatedProfile.assessment.evidence), before);
r = assessWorkflow('Skip for now', r.updatedProfile);
assert.equal(r.blueprint.opportunityScore, null);
assert.equal(r.blueprint.indicativeQuote.expectedPaybackMonths, 'Not yet estimated');
assert.equal(r.updatedProfile.visitorObjective, 'I want to assess automation opportunities across my business');
let c = assessWorkflow('We manually reconcile receipts in Xero');
c = assessWorkflow('Actually we use Sage, not Xero', c.updatedProfile);
assert.equal(c.updatedProfile.primarySystems.includes('Xero'), false);
assert.equal(c.updatedProfile.primarySystems.includes('Sage'), true);
const live = adaptPublicReply({ text: 'A preliminary proposal', tool_outcomes: [{ name: 'generate_solution_blueprint', result: { ok: true, blueprint: { title: 'Close tracking', indicative_quote: { expected_payback_months: '1 month' } } } }] }, r.updatedProfile);
assert.equal(live.responseMode, 'live');
assert.equal(live.blueprint.indicativeQuote.expectedPaybackMonths, 'Not yet estimated');
assert.throws(() => adaptPublicReply({ unexpected: true }, r.updatedProfile));
console.log('Advisor assessment and API contract regression checks passed.');
const { containsSensitivePublicInput } = load('src/lib/public-chat-safety.ts');
for (const value of ['password: example-secret', 'API key=example-secret', 'ID number: 9001011234088', 'opening balance: R100']) assert.equal(containsSensitivePublicInput(value), true);
for (const value of ['We have 30 employees and want payroll automation', 'Do you need bank statements?', 'I want CIPC annual return filing']) assert.equal(containsSensitivePublicInput(value), false);
console.log('Public chat sensitive-input regression checks passed.');
